"use client";
import {useEffect,useMemo,useState} from "react";

type Friend={name:string;face:string;world:string;online:boolean};
type Msg={id:number;from:string;text:string;time:string;gift?:string};
type Note={id:number;icon:string;title:string;text:string;time:string;read:boolean};
const people:Friend[]=[{name:"Mira",face:"👩🏽",world:"Campfire Commons",online:true},{name:"Kairo",face:"🧑🏻",world:"Neon District",online:true},{name:"Orbit",face:"👨🏾",world:"Building a world",online:true},{name:"Pip",face:"👩🏻",world:"Offline",online:false}];
const itemInfo:Record<string,{name:string;icon:string}>={beanie:{name:"Campfire Beanie",icon:"🧢"},crown:{name:"Founder Crown",icon:"👑"},wings:{name:"Cloud Wings",icon:"🪽"},hoodie:{name:"Evergreen Hoodie",icon:"🥼"},spark:{name:"Pocket Spark",icon:"✨"},glasses:{name:"Round Glasses",icon:"👓"},boat:{name:"Tiny Sailboat",icon:"⛵"}};
const starter:Record<string,Msg[]>={Mira:[{id:1,from:"Mira",text:"Hey! Are you coming to story night by the campfire?",time:"10:24"},{id:2,from:"me",text:"Absolutely — save me a log!",time:"10:26"}],Kairo:[{id:3,from:"Kairo",text:"I found a secret route in Neon District 👀",time:"Yesterday"}],Orbit:[{id:4,from:"Orbit",text:"Want to help test my new world later?",time:"Mon"}],Pip:[{id:5,from:"Pip",text:"That fishing trip was so fun!",time:"Sun"}]};
const initialNotes:Note[]=[{id:1,icon:"💬",title:"New message from Kairo",text:"I found a secret route in Neon District",time:"2m",read:false},{id:2,icon:"🔥",title:"Event starts soon",text:"Campfire Story Night begins in 30 minutes",time:"14m",read:false},{id:3,icon:"🏅",title:"Badge progress",text:"You’re one world away from earning Wanderer",time:"1h",read:false},{id:4,icon:"👋",title:"Mira is online",text:"She’s exploring Campfire Commons",time:"2h",read:true}];

export function SocialCenter({username,owned,onGift}:{username:string;owned:string[];onGift:(id:string)=>void}){
 const [tab,setTab]=useState<"messages"|"notifications">("messages"),[selected,setSelected]=useState("Mira"),[threads,setThreads]=useState<Record<string,Msg[]>>(starter),[notes,setNotes]=useState<Note[]>(initialNotes),[draft,setDraft]=useState(""),[giftOpen,setGiftOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false);
 useEffect(()=>{try{const raw=localStorage.getItem("everhome-social");if(raw){const d=JSON.parse(raw);setThreads(d.threads||starter);setNotes(d.notes||initialNotes)}}catch{}},[]);
 useEffect(()=>{localStorage.setItem("everhome-social",JSON.stringify({threads,notes}))},[threads,notes]);
 const unread=notes.filter(n=>!n.read).length,current=threads[selected]||[];
 const previews=useMemo(()=>people.map(p=>({...p,last:(threads[p.name]||[]).at(-1)})),[threads]);
 function send(e:React.FormEvent){e.preventDefault();if(!draft.trim())return;const text=draft.trim();setThreads(t=>({...t,[selected]:[...(t[selected]||[]),{id:Date.now(),from:"me",text,time:"Now"}]}));setDraft("");setTimeout(()=>{const reply=selected==="Mira"?"Perfect! I’ll meet you there ✨":selected==="Kairo"?"Nice — jump into Neon when you're ready!":"Sounds good! See you in EVERHOME.";setThreads(t=>({...t,[selected]:[...(t[selected]||[]),{id:Date.now()+1,from:selected,text:reply,time:"Now"}]}));setNotes(n=>[{id:Date.now(),icon:"💬",title:`New message from ${selected}`,text:reply,time:"Now",read:false},...n])},900)}
 function gift(id:string){const item=itemInfo[id];if(!item)return;onGift(id);setThreads(t=>({...t,[selected]:[...(t[selected]||[]),{id:Date.now(),from:"me",text:`Sent ${item.name}`,gift:id,time:"Now"}]}));setNotes(n=>[{id:Date.now(),icon:"🎁",title:`Gift sent to ${selected}`,text:item.name,time:"Now",read:true},...n]);setGiftOpen(false)}
 return <div className="socialPage"><section className="socialTop"><div><small>STAY CONNECTED</small><h1>Messages & notifications</h1><p>Private conversations, gifts, events, and everything you’ve missed.</p></div><nav><button className={tab==="messages"?"active":""} onClick={()=>setTab("messages")}>💬 Messages</button><button className={tab==="notifications"?"active":""} onClick={()=>{setTab("notifications");setNotes(n=>n.map(x=>({...x,read:true})))}}>🔔 Notifications {unread>0&&<b>{unread}</b>}</button></nav></section>
 {tab==="messages"?<div className={`messenger ${mobileOpen?"threadOpen":""}`}><aside><header><h2>Messages</h2><button onClick={()=>{setSelected("Mira");setMobileOpen(true)}}>＋</button></header><label>⌕ <input placeholder="Find a friend..."/></label>{previews.map(p=><button key={p.name} className={selected===p.name?"selected":""} onClick={()=>{setSelected(p.name);setMobileOpen(true)}}><span>{p.face}<i className={p.online?"online":""}/></span><div><b>{p.name}</b><p>{p.last?.gift?"🎁 Sent a gift":p.last?.text}</p></div><small>{p.last?.time}</small></button>)}</aside><main><header><button className="backMessages" onClick={()=>setMobileOpen(false)}>←</button><span>{people.find(p=>p.name===selected)?.face}</span><div><b>{selected}</b><small>● {people.find(p=>p.name===selected)?.online?people.find(p=>p.name===selected)?.world:"Offline"}</small></div><button onClick={()=>setGiftOpen(!giftOpen)}>•••</button></header><div className="privateMessages"><div className="privacyNote">🔒 Private conversation with {selected}</div>{current.map(m=><div className={`privateBubble ${m.from==="me"?"mine":"theirs"}`} key={m.id}>{m.gift&&<span className="giftBox">{itemInfo[m.gift]?.icon}</span>}<p>{m.text}</p><small>{m.from==="me"?username:m.from} · {m.time}</small></div>)}</div><footer><button className="giftButton" onClick={()=>setGiftOpen(!giftOpen)}>🎁</button><form onSubmit={send}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={`Message ${selected} privately...`}/><button>➤</button></form>{giftOpen&&<div className="giftTray"><header><b>Send a gift to {selected}</b><button onClick={()=>setGiftOpen(false)}>×</button></header>{owned.length?<div>{owned.map(id=><button key={id} onClick={()=>gift(id)}><i>{itemInfo[id]?.icon||"🎁"}</i><span>{itemInfo[id]?.name||id}</span><small>Send</small></button>)}</div>:<p>Your inventory is empty. Visit the Shop to find a gift.</p>}</div>}</footer></main></div>:<div className="notificationCenter"><header><h2>Recent activity</h2><button onClick={()=>setNotes([])}>Clear all</button></header>{notes.length?notes.map(n=><article className={n.read?"":"unread"} key={n.id}><div>{n.icon}</div><section><h3>{n.title}</h3><p>{n.text}</p><small>{n.time} ago</small></section><button onClick={()=>setNotes(x=>x.filter(v=>v.id!==n.id))}>×</button></article>):<div className="emptyNotes">✓<h3>You’re all caught up</h3><p>New messages, gifts, events, and badges will appear here.</p></div>}</div>}
 </div>
}
