"use client";
import {useEffect,useMemo,useRef,useState} from "react";
import {liveDm,liveId,type LiveDm} from "./realtime";
type Note={id:string;icon:string;title:string;text:string;time:string;read:boolean};
const items:Record<string,{name:string;icon:string}>={beanie:{name:"Campfire Beanie",icon:"🧢"},crown:{name:"Founder Crown",icon:"👑"},wings:{name:"Cloud Wings",icon:"🪽"},hoodie:{name:"Evergreen Hoodie",icon:"🥼"},spark:{name:"Pocket Spark",icon:"✨"},glasses:{name:"Round Glasses",icon:"👓"},boat:{name:"Tiny Sailboat",icon:"⛵"}};
export function SocialCenter({username,owned,onGift}:{username:string;owned:string[];onGift:(id:string)=>void}){
 const [tab,setTab]=useState<"messages"|"notifications">("messages"),[messages,setMessages]=useState<LiveDm[]>([]),[selected,setSelected]=useState(""),[find,setFind]=useState(""),[draft,setDraft]=useState(""),[notes,setNotes]=useState<Note[]>([]),[giftOpen,setGiftOpen]=useState(false),[mobileOpen,setMobileOpen]=useState(false),[popup,setPopup]=useState<{name:string;text:string}|null>(null),[online,setOnline]=useState(false);const seen=useRef(new Set<string>()),channel=useRef<BroadcastChannel|null>(null),messagesRef=useRef<LiveDm[]>([]);
 useEffect(()=>{messagesRef.current=messages},[messages]);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem("everhome-live-notes")||"[]");if(Array.isArray(saved))setNotes(saved)}catch{};const accept=(incoming:LiveDm[])=>{const mine=incoming.filter(m=>m&&(m.from===username||m.to.toLowerCase()===username.toLowerCase())).sort((a,b)=>a.at-b.at);setMessages(mine);for(const m of mine){if(seen.current.has(m.id))continue;seen.current.add(m.id);if(m.to.toLowerCase()===username.toLowerCase()&&m.from!==username){setNotes(n=>[{id:m.id,icon:m.gift?"🎁":"💬",title:m.gift?`Gift from ${m.from}`:`New message from ${m.from}`,text:m.text,time:"Now",read:false},...n.filter(x=>x.id!==m.id)]);setPopup({name:m.from,text:m.text})}}};channel.current=typeof BroadcastChannel!=="undefined"?new BroadcastChannel("everhome-social"):null;channel.current.onmessage=e=>accept([...messagesRef.current,e.data]);let alive=true;const poll=async()=>{const data=await liveDm.read();if(alive){setOnline(true);accept(data)}};poll();const timer=setInterval(poll,1500);return()=>{alive=false;clearInterval(timer);channel.current?.close()}},[username]);
 useEffect(()=>{localStorage.setItem("everhome-live-notes",JSON.stringify(notes.slice(0,80)))},[notes]);
 const contacts=useMemo(()=>Array.from(new Set(messages.flatMap(m=>[m.from,m.to]).filter(n=>n&&n!==username))),[messages,username]),current=messages.filter(m=>selected&&((m.from===selected&&m.to===username)||(m.from===username&&m.to===selected))),unread=notes.filter(n=>!n.read).length;
 async function publish(text:string,gift?:string){const to=selected.trim();if(!to||to.toLowerCase()===username.toLowerCase()||!text.trim())return;const m:LiveDm={id:`${liveId()}:${Date.now()}`,from:username,to,text:text.trim().slice(0,300),gift,at:Date.now()};setMessages(v=>[...v,m]);channel.current?.postMessage(m);await liveDm.send(m)}
 function startContact(){const name=find.trim().slice(0,18);if(!name||name.toLowerCase()===username.toLowerCase())return;setSelected(name);setFind("");setMobileOpen(true)}
 function send(e:React.FormEvent){e.preventDefault();if(!draft.trim())return;void publish(draft);setDraft("")}
 function gift(id:string){const item=items[id];if(!item||!selected)return;onGift(id);void publish(`Sent ${item.name}`,id);setGiftOpen(false)}
 return <div className="socialPage"><section className="socialTop"><div><small>LIVE CONNECTIONS</small><h1>Messages & notifications</h1><p>{online?"Connected to EVERHOME realtime.":"Connecting to EVERHOME realtime…"}</p></div><nav><button className={tab==="messages"?"active":""} onClick={()=>setTab("messages")}>💬 Messages</button><button className={tab==="notifications"?"active":""} onClick={()=>{setTab("notifications");setNotes(n=>n.map(x=>({...x,read:true})))}}>🔔 Notifications {unread>0&&<b>{unread}</b>}</button></nav></section>
 {tab==="messages"?<div className={`messenger ${mobileOpen?"threadOpen":""}`}><aside><header><h2>Real messages</h2><button onClick={startContact}>＋</button></header><label>⌕ <input value={find} onChange={e=>setFind(e.target.value)} onKeyDown={e=>{if(e.key==="Enter")startContact()}} placeholder="Enter an exact username…"/></label>{contacts.length?contacts.map(name=>{const last=messages.filter(m=>m.from===name||m.to===name).at(-1);return <button key={name} className={selected===name?"selected":""} onClick={()=>{setSelected(name);setMobileOpen(true)}}><span>◉<i className="online"/></span><div><b>{name}</b><p>{last?.gift?"🎁 Gift":last?.text}</p></div><small>Live</small></button>}):<div className="emptyThreads"><b>No conversations yet</b><p>Enter a real player&apos;s exact username above.</p></div>}</aside>{selected?<main><header><button className="backMessages" onClick={()=>setMobileOpen(false)}>←</button><span>◉</span><div><b>{selected}</b><small>Realtime direct chat</small></div><button onClick={()=>setGiftOpen(!giftOpen)}>•••</button></header><div className="privateMessages"><div className="privacyNote">Direct conversation with {selected}</div>{current.map(m=><div className={`privateBubble ${m.from===username?"mine":"theirs"}`} key={m.id}>{m.gift&&<span className="giftBox">{items[m.gift]?.icon}</span>}<p>{m.text}</p><small>{m.from} · {new Date(m.at).toLocaleTimeString([],{hour:"2-digit",minute:"2-digit"})}</small></div>)}</div><footer><button className="giftButton" onClick={()=>setGiftOpen(!giftOpen)}>🎁</button><form onSubmit={send}><input value={draft} onChange={e=>setDraft(e.target.value)} placeholder={`Message ${selected} privately…`}/><button>➤</button></form>{giftOpen&&<div className="giftTray"><header><b>Send a gift to {selected}</b><button onClick={()=>setGiftOpen(false)}>×</button></header>{owned.length?<div>{owned.map(id=><button key={id} onClick={()=>gift(id)}><i>{items[id]?.icon||"🎁"}</i><span>{items[id]?.name||id}</span><small>Send</small></button>)}</div>:<p>Your inventory is empty.</p>}</div>}</footer></main>:<main className="emptyConversation"><b>Start a real conversation</b><p>There are no NPC or sample accounts here.</p></main>}</div>:<div className="notificationCenter"><header><h2>Realtime activity</h2><button onClick={()=>setNotes([])}>Clear all</button></header>{notes.length?notes.map(n=><article className={n.read?"":"unread"} key={n.id}><div>{n.icon}</div><section><h3>{n.title}</h3><p>{n.text}</p><small>{n.time}</small></section><button onClick={()=>setNotes(x=>x.filter(v=>v.id!==n.id))}>×</button></article>):<div className="emptyNotes">✓<h3>You&apos;re all caught up</h3><p>Real messages and gifts will appear here instantly.</p></div>}</div>}
 {popup&&<aside className="fishDmPopup"><header><b>💬 {popup.name}</b><button onClick={()=>setPopup(null)}>✕</button></header><p>{popup.text}</p><footer><button onClick={()=>{setTab("messages");setSelected(popup.name);setMobileOpen(true);setPopup(null)}}>💬 Reply</button></footer></aside>}</div>
}
