"use client";
import {useEffect,useRef,useState} from "react";
import {liveChat,liveId,livePresence,type LiveChat,type LivePresence} from "./realtime";
import {activeNpcsForWorld} from "./npc-system";

type World={id:string;name:string;icon:string;theme:string;players:number;kind:string;description:string};
type Avatar={skin:string;hair:string;top:string;bottom:string;face:string;hat:string;model?:string};
type Catch={name:string;icon:string;size:number;rare:string};
type FishState="idle"|"waiting"|"reeling"|"caught";
const TAU=Math.PI*2, clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const palettes:Record<string,{sky:string;far:string;ground:string;edge:string;path:string;water?:string;glow:string}>={
 forest:{sky:"#8de7dc",far:"#61bba2",ground:"#52a86b",edge:"#28664b",path:"#e5c987",glow:"#ffd36b"},
 lake:{sky:"#8bdcff",far:"#438ec7",ground:"#3c9563",edge:"#195f65",path:"#d9b674",water:"#1477b8",glow:"#67e8ff"},
 coast:{sky:"#ffc797",far:"#d77783",ground:"#61a36f",edge:"#276b69",path:"#f3c983",water:"#167db1",glow:"#ffbe69"},
 neon:{sky:"#161738",far:"#37236d",ground:"#292455",edge:"#171331",path:"#6752a4",glow:"#41e5dd"},
 sky:{sky:"#a6e5ff",far:"#74bce8",ground:"#8fcf83",edge:"#527e86",path:"#f4e7bf",glow:"#ffffff"},
 cafe:{sky:"#ffd7d0",far:"#d88686",ground:"#bf8f78",edge:"#754e4d",path:"#ffe2b6",glow:"#ff869b"},
 arcade:{sky:"#251642",far:"#54266e",ground:"#293667",edge:"#151733",path:"#7158a8",glow:"#ff4fa7"}
};
const props=[[-430,-280,"🌲"],[-210,-390,"🌲"],[350,-320,"🌲"],[480,-50,"🌲"],[-500,190,"🌲"],[-260,360,"🌲"],[290,350,"🌲"],[520,220,"🌲"],[-80,-280,"🪨"],[210,120,"🌼"],[0,260,"🪵"]] as const;
const WORLD_W=4000,WORLD_H=2700;
const FISH_ISLANDS=[{id:"coconut",name:"Coconut Bay",x:650,y:620,r:340,theme:"tropical",icon:"🌴"},{id:"crescent",name:"Crescent Isle",x:1750,y:480,r:330,theme:"tropical",icon:"🌺"},{id:"volcanic",name:"Volcanic Depths",x:430,y:1800,r:350,theme:"volcanic",icon:"🌋"},{id:"luxian",name:"Luxian Dunes",x:1780,y:1780,r:370,theme:"desert",icon:"🏜️"},{id:"tanglewood",name:"Tanglewood",x:2920,y:1030,r:330,theme:"swamp",icon:"🌿"},{id:"twilight",name:"Twilight Realm",x:3250,y:2050,r:340,theme:"twilight",icon:"🌙"},{id:"altar",name:"The Altar",x:2250,y:330,r:95,theme:"rock",icon:"💎"},{id:"lighthouse",name:"Lighthouse",x:3670,y:1110,r:235,theme:"lighthouse",icon:"🗼"}] as const;
const ISLAND_COLORS:Record<string,[string,string,string]>={tropical:["#f0d997","#51ad65","#2c7542"],volcanic:["#493b37","#3d3b40","#ff7041"],desert:["#ead49b","#d0ae5c","#9d7834"],swamp:["#687151","#38553a","#1d3424"],twilight:["#6c56a0","#55417f","#2e2454"],rock:["#a9b0b7","#777e87","#4b535e"],lighthouse:["#d9cfae","#6f8d72","#435e53"]};

export function EverhomeWorldEngine({world,username,avatar,onExit,onVisit,onChat}:{world:World;username:string;avatar:Avatar;onExit:()=>void;onVisit:(id:string)=>void;onChat:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),mapCanvas=useRef<HTMLCanvasElement>(null),actor=useRef({x:650,y:620,head:0,speed:0}),cam=useRef({x:650,y:620}),keys=useRef(new Set<string>()),joy=useRef({x:0,y:0}),hold=useRef(false),fishRef=useRef<{state:FishState;at:number;marker:number;zone:number;progress:number}>({state:"idle",at:0,marker:.5,zone:.5,progress:0}),seenChat=useRef(new Set<string>()),chatChannel=useRef<BroadcastChannel|null>(null),presenceChannel=useRef<BroadcastChannel|null>(null),remotePlayers=useRef<LivePresence[]>([]);
 const [chat,setChat]=useState(false),[message,setMessage]=useState(""),[bubble,setBubble]=useState(""),[log,setLog]=useState<string[]>([]),[people,setPeople]=useState(false),[unread,setUnread]=useState(0),[liveReady,setLiveReady]=useState(false),[onlineCount,setOnlineCount]=useState(1),[fishState,setFishState]=useState<FishState>("idle"),[status,setStatus]=useState("Sail to a fishing spot and cast."),[bag,setBag]=useState<Catch[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem("everhome-lake-catches")||"[]")}catch{return[]}}),[reel,setReel]=useState({marker:.5,zone:.5,progress:0});
 const lake=world.id==="lake", theme=palettes[world.theme]||palettes.forest;
 useEffect(()=>{onVisit(world.id)},[onVisit,world.id]);
 useEffect(()=>{const accept=(all:LiveChat[])=>{const fresh=all.filter(m=>m?.id&&m.world===world.id&&Date.now()-m.at<3600000).sort((a,b)=>a.at-b.at);setLog(fresh.slice(-60).map(m=>`${m.name}: ${m.text}`));let added=0;for(const m of fresh){if(!seenChat.current.has(m.id)){seenChat.current.add(m.id);if(m.name!==username)added++}}if(added&&!chat)setUnread(n=>n+added)};chatChannel.current=typeof BroadcastChannel!=="undefined"?new BroadcastChannel(`everhome-world-${world.id}`):null;chatChannel.current.onmessage=e=>{const m=e.data as LiveChat;if(!m||m.world!==world.id||seenChat.current.has(m.id))return;seenChat.current.add(m.id);setLog(l=>[...l.slice(-59),`${m.name}: ${m.text}`]);if(m.name!==username&&!chat)setUnread(n=>n+1)};let alive=true;const poll=async()=>{const data=await liveChat.read();if(alive){setLiveReady(true);accept(data)}};poll();const timer=setInterval(poll,1400);return()=>{alive=false;clearInterval(timer);chatChannel.current?.close()}},[chat,username,world.id]);

 useEffect(()=>{const id=liveId(),accept=(all:LivePresence[])=>{const now=Date.now(),byId=new Map<string,LivePresence>();for(const p of all)if(p?.id&&p.id!==id&&p.world===world.id&&now-p.at<22000&&(!byId.has(p.id)||byId.get(p.id)!.at<p.at))byId.set(p.id,p);const fresh=[...byId.values()];remotePlayers.current=fresh;setOnlineCount(1+fresh.length)};presenceChannel.current=typeof BroadcastChannel!=="undefined"?new BroadcastChannel(`everhome-presence-${world.id}`):null;presenceChannel.current.onmessage=e=>accept([...(remotePlayers.current||[]),e.data as LivePresence]);let alive=true;const sync=async()=>{const a=actor.current,me:LivePresence={id,name:username,world:world.id,x:Math.round(a.x),y:Math.round(a.y),head:a.head,color:"#32d8ff",at:Date.now()};presenceChannel.current?.postMessage(me);void livePresence.send(me);const all=await livePresence.read();if(alive)accept(all)};sync();const timer=setInterval(sync,1200);return()=>{alive=false;clearInterval(timer);presenceChannel.current?.close();remotePlayers.current=[]}},[username,world.id]);

 useEffect(()=>{localStorage.setItem("everhome-lake-catches",JSON.stringify(bag))},[bag]);
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea"))return;keys.current.add(e.code);if(e.code==="Space"){e.preventDefault();hold.current=true;if(lake&&fishRef.current.state==="idle")cast()}};
  const up=(e:KeyboardEvent)=>{keys.current.delete(e.code);if(e.code==="Space")hold.current=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)};
 },[lake]);
 function cast(){const f=fishRef.current;if(f.state!=="idle")return;f.state="waiting";f.at=performance.now()+1400+Math.random()*1700;setFishState("waiting");setStatus("Your float bobs on the water… wait for the bite!")}
 function finishCatch(){const pool=[{name:"Bluegill",icon:"🐟",rare:"Common"},{name:"Moon Koi",icon:"🐠",rare:"Uncommon"},{name:"Lake Sturgeon",icon:"🐡",rare:"Rare"},{name:"Homewater Spirit",icon:"✨",rare:"Legendary"}],roll=Math.random(),pick=pool[roll>.96?3:roll>.78?2:roll>.42?1:0],caught={...pick,size:Math.round((14+Math.random()*83)*10)/10};setBag(b=>[...b,caught]);setBubble(`I caught a ${caught.name}! 🎣`);setTimeout(()=>setBubble(""),4000);fishRef.current.state="caught";setFishState("caught");setStatus(`${caught.icon} ${caught.name} · ${caught.size} cm · ${caught.rare}!`);setTimeout(()=>{fishRef.current.state="idle";setFishState("idle");setStatus("Great catch! Cast again when ready.")},1800)}
 useEffect(()=>{
  const c=canvas.current;if(!c)return;const ctx=c.getContext("2d")!;let frame=0,last=performance.now(),w=innerWidth,h=innerHeight,dpr=1;
  const resize=()=>{w=innerWidth;h=innerHeight;dpr=Math.min(2,devicePixelRatio||1);c.width=w*dpr;c.height=h*dpr;c.style.width=w+"px";c.style.height=h+"px"};resize();addEventListener("resize",resize);
  const iso=(x:number,y:number,z=0)=>{const dx=x-cam.current.x,dy=y-cam.current.y;return{x:w/2+(dx-dy)*.72,y:h*.52+(dx+dy)*.32-z}};
  const ellipse=(x:number,y:number,rx:number,ry:number,color:string)=>{ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill()};
  const avatarDraw=(x:number,y:number,head:number)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle="rgba(18,31,44,.22)";ctx.beginPath();ctx.ellipse(0,7,22,8,0,0,TAU);ctx.fill();if(lake){ctx.rotate(head-.78);ctx.fillStyle="#9b6035";ctx.beginPath();ctx.moveTo(-29,7);ctx.quadraticCurveTo(0,23,29,7);ctx.lineTo(19,-9);ctx.lineTo(-19,-9);ctx.closePath();ctx.fill();ctx.fillStyle="#f4c258";ctx.fillRect(-3,-17,6,20);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(0,-23,8,0,TAU);ctx.fill()}else{ctx.fillStyle=avatar.bottom;ctx.beginPath();ctx.roundRect(-12,-20,9,25,5);ctx.roundRect(3,-20,9,25,5);ctx.fill();ctx.fillStyle=avatar.top;ctx.beginPath();ctx.roundRect(-17,-48,34,33,12);ctx.fill();ctx.fillStyle=avatar.skin;ctx.beginPath();ctx.roundRect(-22,-43,7,24,5);ctx.roundRect(15,-43,7,24,5);ctx.fill();ctx.beginPath();ctx.arc(0,-64,19,0,TAU);ctx.fill();ctx.fillStyle=avatar.hair;ctx.beginPath();ctx.arc(0,-68,19,Math.PI,TAU);ctx.quadraticCurveTo(19,-54,15,-50);ctx.lineTo(10,-64);ctx.quadraticCurveTo(0,-57,-10,-64);ctx.lineTo(-15,-50);ctx.quadraticCurveTo(-19,-55,-19,-68);ctx.fill();ctx.fillStyle="#263241";ctx.beginPath();ctx.arc(-6,-64,2.2,0,TAU);ctx.arc(6,-64,2.2,0,TAU);ctx.fill();ctx.strokeStyle="#b55b62";ctx.lineWidth=1.5;ctx.beginPath();ctx.arc(0,-59,5,.2,Math.PI-.2);ctx.stroke();ctx.fillStyle="rgba(255,126,130,.35)";ctx.beginPath();ctx.ellipse(-11,-59,4,2,0,0,TAU);ctx.ellipse(11,-59,4,2,0,0,TAU);ctx.fill()}ctx.restore()};
  const drawMap=()=>{const mc=mapCanvas.current;if(!mc)return;const m=mc.getContext("2d")!,mw=mc.width,mh=mc.height,sx=mw/WORLD_W,sy=mh/WORLD_H;m.clearRect(0,0,mw,mh);const g=m.createLinearGradient(0,0,0,mh);g.addColorStop(0,"#183f62");g.addColorStop(1,"#09243b");m.fillStyle=g;m.fillRect(0,0,mw,mh);m.strokeStyle="rgba(109,220,255,.13)";m.lineWidth=1;for(let x=0;x<WORLD_W;x+=500){m.beginPath();m.moveTo(x*sx,0);m.lineTo(x*sx,mh);m.stroke()}for(let y=0;y<WORLD_H;y+=500){m.beginPath();m.moveTo(0,y*sy);m.lineTo(mw,y*sy);m.stroke()}FISH_ISLANDS.forEach(i=>{const colors=ISLAND_COLORS[i.theme];m.fillStyle=colors[0];m.beginPath();m.ellipse(i.x*sx,i.y*sy,Math.max(3,i.r*sx),Math.max(2,i.r*sy),0,0,TAU);m.fill();m.fillStyle=colors[1];m.beginPath();m.ellipse(i.x*sx,i.y*sy,Math.max(2,i.r*sx*.78),Math.max(1,i.r*sy*.78),0,0,TAU);m.fill()});for(const p of remotePlayers.current){m.fillStyle=p.color||"#ff78c8";m.beginPath();m.arc(p.x*sx,p.y*sy,3.4,0,TAU);m.fill();m.strokeStyle="#fff";m.lineWidth=1;m.stroke()}const a=actor.current,ax=a.x*sx,ay=a.y*sy;m.save();m.translate(ax,ay);m.rotate(a.head);m.fillStyle="#ffe16b";m.strokeStyle="#172c44";m.lineWidth=1.5;m.beginPath();m.moveTo(0,-6);m.lineTo(4.5,5);m.lineTo(0,3);m.lineTo(-4.5,5);m.closePath();m.fill();m.stroke();m.restore();m.strokeStyle="rgba(255,255,255,.6)";m.lineWidth=1;m.strokeRect(clamp(ax-(w*.5/1.44)*sx,0,mw),clamp(ay-(h*.5/.64)*sy,0,mh),Math.min(mw,w/1.44*sx),Math.min(mh,h/.64*sy))};
  const drawWorld=(t:number)=>{const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,"#b9ebff");grad.addColorStop(.5,theme.sky);grad.addColorStop(1,"#51afd0");ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.3;for(let i=0;i<7;i++){ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(((i*241+t*.008)%(w+260))-130,70+(i%3)*48,80,18,0,0,TAU);ctx.ellipse(((i*241+t*.008)%(w+260))-95,65+(i%3)*48,38,25,0,0,TAU);ctx.fill()}ctx.globalAlpha=1;ctx.strokeStyle="rgba(255,255,255,.16)";ctx.lineWidth=2;for(let i=0;i<10;i++){const wy=(i*83+t*.012)%h;ctx.beginPath();ctx.arc((i*317)%w,wy,18+i%3*9,.1,Math.PI*.9);ctx.stroke()}
   ctx.textAlign="center";FISH_ISLANDS.forEach((island,index)=>{const p=iso(island.x,island.y),colors=ISLAND_COLORS[island.theme],rx=island.r*1.02,ry=island.r*.46;if(p.x+rx<-80||p.x-rx>w+80||p.y+ry<0||p.y-ry>h+100)return;ellipse(p.x,p.y+25,rx,ry,colors[2]);ellipse(p.x,p.y+10,rx*.99,ry*.98,"#f7dda0");ellipse(p.x,p.y,rx*.84,ry*.8,colors[1]);ctx.strokeStyle="rgba(255,255,255,.5)";ctx.lineWidth=4;ctx.beginPath();ctx.ellipse(p.x,p.y+5,rx*.91,ry*.88,0,0,TAU);ctx.stroke();for(let n=0;n<(island.r<150?1:7);n++){const angle=n*2.31+index*.7,q=iso(island.x+Math.cos(angle)*island.r*.5,island.y+Math.sin(angle)*island.r*.5),decor=island.theme==="volcanic"?(n===0?"🌋":"🪨"):island.theme==="twilight"?(n%2?"🍄":"✨"):island.theme==="desert"?(n%2?"🌼":"🌵"):island.theme==="swamp"?(n%2?"🌳":"🌿"):island.theme==="lighthouse"?(n===0?"🗼":"🌲"):(n%3===0?"🌸":"🌳");ctx.font=`${30+n%3*4}px system-ui`;ctx.fillText(decor,q.x,q.y)}if(island.r>200){const home=iso(island.x-island.r*.13,island.y-island.r*.08);ctx.font="42px system-ui";ctx.fillText(index%3===0?"🏡":index%3===1?"🏕️":"🛖",home.x,home.y);const flower=iso(island.x+island.r*.12,island.y+island.r*.1);ctx.font="22px system-ui";ctx.fillText("🌷  🌼  🌷",flower.x,flower.y)}ctx.font="900 12px system-ui";ctx.fillStyle="#fff";ctx.shadowColor="#28485a";ctx.shadowBlur=7;ctx.fillText(`${island.icon} ${island.name}`,p.x,p.y-ry*.68);ctx.shadowBlur=0});
   for(const other of remotePlayers.current){const q=iso(other.x,other.y);avatarDraw(q.x,q.y,other.head);ctx.font="800 12px system-ui";ctx.fillStyle=other.color||"#75ecff";ctx.shadowColor="#102739";ctx.shadowBlur=5;ctx.fillText(other.name,q.x,q.y-(lake?40:80));ctx.shadowBlur=0}
   const p=iso(actor.current.x,actor.current.y),stepBob=actor.current.speed>8?Math.abs(Math.sin(t*.011))*4:0;avatarDraw(p.x,p.y-stepBob,actor.current.head);ctx.font="800 13px system-ui";ctx.fillStyle="#fff";ctx.shadowColor="#102739";ctx.shadowBlur=5;ctx.fillText(username,p.x,p.y-(lake?40:80)-stepBob);ctx.shadowBlur=0;if(bubble){const bw=Math.min(240,Math.max(92,bubble.length*7));ctx.fillStyle="#fff";ctx.beginPath();ctx.roundRect(p.x-bw/2,p.y-(lake?94:135)-stepBob,bw,35,14);ctx.fill();ctx.fillStyle="#243348";ctx.font="600 12px system-ui";ctx.fillText(bubble,p.x,p.y-(lake?72:113)-stepBob)}drawMap()
  };
  const loop=(t:number)=>{const dt=Math.min(.05,(t-last)/1000);last=t;const k=keys.current,j=joy.current,ix=(k.has("KeyD")||k.has("ArrowRight")?1:0)-(k.has("KeyA")||k.has("ArrowLeft")?1:0)+j.x,iy=(k.has("KeyS")||k.has("ArrowDown")?1:0)-(k.has("KeyW")||k.has("ArrowUp")?1:0)+j.y,mag=Math.min(1,Math.hypot(ix,iy));const a=actor.current;if(mag>.04){const target=Math.atan2(ix,-iy);let diff=target-a.head;while(diff>Math.PI)diff-=TAU;while(diff<-Math.PI)diff+=TAU;a.head+=diff*Math.min(1,dt*9);a.speed=Math.min(lake?190:210,a.speed+(lake?125:420)*dt)}else a.speed=Math.max(0,a.speed-(lake?165:540)*dt);a.x+=Math.sin(a.head)*a.speed*dt;a.y-=Math.cos(a.head)*a.speed*dt;a.x=clamp(a.x,35,WORLD_W-35);a.y=clamp(a.y,35,WORLD_H-35);cam.current.x+=(a.x-cam.current.x)*Math.min(1,dt*5);cam.current.y+=(a.y-cam.current.y)*Math.min(1,dt*5);
   const f=fishRef.current;if(f.state==="waiting"&&t>=f.at){f.state="reeling";f.progress=.12;f.zone=.2+Math.random()*.6;setFishState("reeling");setStatus("BITE! Hold REEL or Space — keep the fish in the glowing zone!")}else if(f.state==="reeling"){f.marker=clamp(f.marker+(hold.current?-.62:.43)*dt,0,1);f.zone=clamp(f.zone+Math.sin(t*.003)*.16*dt,0.16,.84);const good=Math.abs(f.marker-f.zone)<.16;f.progress=clamp(f.progress+(good?.34:-.17)*dt,0,1);setReel({marker:f.marker,zone:f.zone,progress:f.progress});if(f.progress>=1)finishCatch();else if(f.progress<=0){f.state="idle";setFishState("idle");setStatus("The fish escaped — cast again!")}}
   ctx.setTransform(dpr,0,0,dpr,0,0);drawWorld(t);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);removeEventListener("resize",resize)};
 },[avatar,bubble,lake,theme,username,world.icon,world.name,world.theme]);
 function send(e:React.FormEvent){e.preventDefault();const text=message.trim();if(!text)return;const m:LiveChat={id:`${liveId()}:${Date.now()}`,name:username,text:text.slice(0,120),world:world.id,at:Date.now()};seenChat.current.add(m.id);setLog(l=>[...l.slice(-59),`${username}: ${m.text}`]);chatChannel.current?.postMessage(m);void liveChat.send(m);setBubble(m.text);setMessage("");onChat();setTimeout(()=>setBubble(""),5000)}
 function joyStart(e:React.PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),move=(x:number,y:number)=>{joy.current={x:clamp((x-(r.left+r.width/2))/48,-1,1),y:clamp((y-(r.top+r.height/2))/48,-1,1)}};move(e.clientX,e.clientY)}
 return <main className="ehEngine"><canvas ref={canvas}/><header className="ehWorldHud"><button onClick={onExit}>← Leave</button><div><b>{world.icon} {world.name}</b><small>4000 × 2700 WORLD · {lake?"FISHING GAME":"EXPLORE"} · {onlineCount} ONLINE</small></div><button onClick={()=>setPeople(!people)}>♙ People {onlineCount}</button></header><canvas ref={mapCanvas} className="ehMinimap" width="260" height="176"/><div className="ehNameplate"><span>◆ EXPLORER</span><b>{username}</b></div><div className="ehJoy" onPointerDown={joyStart} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))joyStart(e)}} onPointerUp={e=>{joy.current={x:0,y:0};e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>joy.current={x:0,y:0}}><i style={{transform:`translate(calc(-50% + ${joy.current.x*38}px),calc(-50% + ${joy.current.y*38}px))`}}/></div><div className="ehHint">WASD / arrows · drag joystick to explore the full archipelago</div>
 {lake&&<aside className="ehFishing"><header><div><small>EVERHOME MINI GAME</small><b>🎣 THE LAKE</b></div><span>🎒 {bag.length}</span></header><p>{status}</p>{fishState==="reeling"&&<div className="reelGame"><div className="reelTrack"><i style={{top:`${reel.zone*100}%`}}/><b style={{top:`${reel.marker*100}%`}}>🐟</b></div><div className="reelProgress"><i style={{width:`${reel.progress*100}%`}}/></div></div>}<button disabled={fishState==="waiting"||fishState==="caught"} onClick={()=>fishState==="idle"?cast():null} onPointerDown={()=>hold.current=true} onPointerUp={()=>hold.current=false} onPointerCancel={()=>hold.current=false}>{fishState==="idle"?"🎣 CAST LINE":fishState==="waiting"?"〰 WAITING…":"⬆ HOLD TO REEL"}</button>{bag.length>0&&<div className="catchStrip">{bag.slice(-3).reverse().map((f,i)=><span key={i}>{f.icon} <b>{f.name}</b><small>{f.size} cm</small></span>)}</div>}</aside>}
 <button className="fishChatChip ehChatButton" onClick={()=>{setChat(!chat);setUnread(0)}}>💬{unread>0&&<span className="fishUnread">{unread>9?"9+":unread}</span>}<span className="fishOnline">{liveReady?"●":"…"}</span></button>{chat&&<section className="fishChatPanel ehChat"><header><b>💬 World Chat</b><span>{liveReady?"🟢 Realtime connected":"Connecting…"}</span><button onClick={()=>setChat(false)}>✕</button></header><div className="fishChatLog">{log.map((m,i)=>{const n=m.split(":")[0],text=m.slice(m.indexOf(":")+1);return <p className={n===username?"mine":""} key={i}><b>{n}</b> <span>{text}</span></p>})}</div><form onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Say something…" maxLength={120}/><button>➤</button></form></section>}{people&&<aside className="ehPeople"><header><b>People here · {onlineCount}</b><button onClick={()=>setPeople(false)}>×</button></header>{activeNpcsForWorld(world.id).map(n=><p key={n.id}>{n.face} <b>{n.name}</b><small>NPC</small></p>)}{remotePlayers.current.map(p=><p key={p.id}>🟢 <b>{p.name}</b><small>{Math.round(p.x)}, {Math.round(p.y)}</small></p>)}<p>🙂 <b>{username}</b><small>You</small></p></aside>}</main>
}
