"use client";
import {useEffect,useRef,useState} from "react";

type World={id:string;name:string;icon:string;theme:string;players:number;kind:string;description:string};
type Avatar={skin:string;hair:string;top:string;bottom:string;face:string;hat:string;model?:string};
type Catch={name:string;icon:string;size:number;rare:string};
type FishState="idle"|"waiting"|"reeling"|"caught";
const TAU=Math.PI*2, clamp=(n:number,a:number,b:number)=>Math.max(a,Math.min(b,n));
const palettes:Record<string,{sky:string;far:string;ground:string;edge:string;path:string;water?:string;glow:string}>={
 forest:{sky:"#8de7dc",far:"#61bba2",ground:"#52a86b",edge:"#28664b",path:"#e5c987",glow:"#ffd36b"},
 lake:{sky:"#8bdcff",far:"#438ec7",ground:"#3c9563",edge:"#195f65",path:"#d9b674",water:"#1477b8",glow:"#67e8ff"},
 coast:{sky:"#ffc797",far:"#d77783",ground:"#61a36f",edge:"#276b69",path:"#f3c983",water:"#167db1",glow:"#ffbe69"},
 neon:{sky:"#161738",far:"#37236d",ground:"#292455",edge:"#171331",path:"#6752a4",glow:"#41e5dd"},
 sky:{sky:"#a6e5ff",far:"#74bce8",ground:"#8fcf83",edge:"#527e86",path:"#f4e7bf",glow:"#ffffff"},
 cafe:{sky:"#ffd7d0",far:"#d88686",ground:"#bf8f78",edge:"#754e4d",path:"#ffe2b6",glow:"#ff869b"},
 arcade:{sky:"#251642",far:"#54266e",ground:"#293667",edge:"#151733",path:"#7158a8",glow:"#ff4fa7"}
};
const props=[[-430,-280,"🌲"],[-210,-390,"🌲"],[350,-320,"🌲"],[480,-50,"🌲"],[-500,190,"🌲"],[-260,360,"🌲"],[290,350,"🌲"],[520,220,"🌲"],[-80,-280,"🪨"],[210,120,"🌼"],[0,260,"🪵"]] as const;

export function EverhomeWorldEngine({world,username,avatar,onExit,onVisit,onChat}:{world:World;username:string;avatar:Avatar;onExit:()=>void;onVisit:(id:string)=>void;onChat:()=>void}){
 const canvas=useRef<HTMLCanvasElement>(null),actor=useRef({x:0,y:150,head:0,speed:0}),cam=useRef({x:0,y:150}),keys=useRef(new Set<string>()),joy=useRef({x:0,y:0}),hold=useRef(false),fishRef=useRef<{state:FishState;at:number;marker:number;zone:number;progress:number}>({state:"idle",at:0,marker:.5,zone:.5,progress:0});
 const [chat,setChat]=useState(false),[message,setMessage]=useState(""),[bubble,setBubble]=useState("Welcome home!"),[log,setLog]=useState(["Mira: This world feels alive!","Kairo: Use the joystick to explore 👋"]),[people,setPeople]=useState(false),[fishState,setFishState]=useState<FishState>("idle"),[status,setStatus]=useState("Sail to a fishing spot and cast."),[bag,setBag]=useState<Catch[]>(()=>{if(typeof window==="undefined")return[];try{return JSON.parse(localStorage.getItem("everhome-lake-catches")||"[]")}catch{return[]}}),[reel,setReel]=useState({marker:.5,zone:.5,progress:0});
 const lake=world.id==="lake", theme=palettes[world.theme]||palettes.forest;
 useEffect(()=>{onVisit(world.id)},[onVisit,world.id]);
 useEffect(()=>{localStorage.setItem("everhome-lake-catches",JSON.stringify(bag))},[bag]);
 useEffect(()=>{
  const down=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.matches("input,textarea"))return;keys.current.add(e.code);if(e.code==="Space"){e.preventDefault();hold.current=true;if(lake&&fishRef.current.state==="idle")cast()}};
  const up=(e:KeyboardEvent)=>{keys.current.delete(e.code);if(e.code==="Space")hold.current=false};window.addEventListener("keydown",down);window.addEventListener("keyup",up);return()=>{window.removeEventListener("keydown",down);window.removeEventListener("keyup",up)};
 },[lake]);
 function cast(){const f=fishRef.current;if(f.state!=="idle")return;f.state="waiting";f.at=performance.now()+1400+Math.random()*1700;setFishState("waiting");setStatus("Your float bobs on the water… wait for the bite!")}
 function finishCatch(){const pool=[{name:"Bluegill",icon:"🐟",rare:"Common"},{name:"Moon Koi",icon:"🐠",rare:"Uncommon"},{name:"Lake Sturgeon",icon:"🐡",rare:"Rare"},{name:"Homewater Spirit",icon:"✨",rare:"Legendary"}],roll=Math.random(),pick=pool[roll>.96?3:roll>.78?2:roll>.42?1:0],caught={...pick,size:Math.round((14+Math.random()*83)*10)/10};setBag(b=>[...b,caught]);setBubble(`I caught a ${caught.name}! 🎣`);setTimeout(()=>setBubble(""),4000);fishRef.current.state="caught";setFishState("caught");setStatus(`${caught.icon} ${caught.name} · ${caught.size} cm · ${caught.rare}!`);setTimeout(()=>{fishRef.current.state="idle";setFishState("idle");setStatus("Great catch! Cast again when ready.")},1800)}
 useEffect(()=>{
  const c=canvas.current;if(!c)return;const ctx=c.getContext("2d")!;let frame=0,last=performance.now(),w=innerWidth,h=innerHeight,dpr=1;
  const resize=()=>{w=innerWidth;h=innerHeight;dpr=Math.min(2,devicePixelRatio||1);c.width=w*dpr;c.height=h*dpr;c.style.width=w+"px";c.style.height=h+"px"};resize();addEventListener("resize",resize);
  const iso=(x:number,y:number,z=0)=>{const dx=x-cam.current.x,dy=y-cam.current.y;return{x:w/2+(dx-dy)*.72,y:h*.52+(dx+dy)*.32-z}};
  const ellipse=(x:number,y:number,rx:number,ry:number,color:string)=>{ctx.fillStyle=color;ctx.beginPath();ctx.ellipse(x,y,rx,ry,0,0,TAU);ctx.fill()};
  const avatarDraw=(x:number,y:number,head:number)=>{ctx.save();ctx.translate(x,y);ctx.fillStyle="rgba(18,31,44,.25)";ctx.beginPath();ctx.ellipse(0,7,20,7,0,0,TAU);ctx.fill();if(lake){ctx.rotate(head-.78);ctx.fillStyle="#8a4f2a";ctx.beginPath();ctx.moveTo(-27,7);ctx.quadraticCurveTo(0,22,27,7);ctx.lineTo(18,-8);ctx.lineTo(-18,-8);ctx.closePath();ctx.fill();ctx.fillStyle="#f4c258";ctx.fillRect(-3,-17,6,20);ctx.fillStyle="#fff";ctx.beginPath();ctx.arc(0,-23,7,0,TAU);ctx.fill()}else{ctx.fillStyle=avatar.bottom;ctx.fillRect(-10,-18,7,22);ctx.fillRect(3,-18,7,22);ctx.fillStyle=avatar.top;ctx.beginPath();ctx.roundRect(-14,-44,28,29,8);ctx.fill();ctx.fillStyle=avatar.skin;ctx.fillRect(-19,-40,6,23);ctx.fillRect(13,-40,6,23);ctx.beginPath();ctx.arc(0,-56,14,0,TAU);ctx.fill();ctx.fillStyle=avatar.hair;ctx.beginPath();ctx.arc(0,-60,14,Math.PI,TAU);ctx.fill();ctx.fillStyle="#263241";ctx.font="bold 8px sans-serif";ctx.textAlign="center";ctx.fillText(avatar.face,0,-53)}ctx.restore()};
  const drawWorld=(t:number)=>{const grad=ctx.createLinearGradient(0,0,0,h);grad.addColorStop(0,theme.sky);grad.addColorStop(.55,theme.far);grad.addColorStop(1,"#163449");ctx.fillStyle=grad;ctx.fillRect(0,0,w,h);ctx.globalAlpha=.22;for(let i=0;i<7;i++){ctx.fillStyle="#fff";ctx.beginPath();ctx.ellipse(((i*241+t*.008)% (w+260))-130,80+(i%3)*54,80,18,0,0,TAU);ctx.fill()}ctx.globalAlpha=1;
   const center=iso(0,0);if(lake){ellipse(center.x,center.y+24,720,360,theme.edge);ellipse(center.x,center.y,700,350,theme.water!);ctx.strokeStyle="rgba(180,240,255,.25)";ctx.lineWidth=2;for(let i=0;i<9;i++){ctx.beginPath();ctx.ellipse(center.x,center.y,(90+i*68)+(Math.sin(t*.002+i)*9),42+i*32,0,0,TAU);ctx.stroke()}}else{ellipse(center.x,center.y+28,720,360,theme.edge);ellipse(center.x,center.y,700,350,theme.ground);ctx.strokeStyle=theme.path;ctx.lineWidth=54;ctx.lineCap="round";ctx.beginPath();ctx.moveTo(...Object.values(iso(-580,120)));ctx.quadraticCurveTo(center.x,center.y-80,...Object.values(iso(550,-160)));ctx.stroke()}
   const landmark=iso(0,-80);ctx.textAlign="center";ctx.font="64px system-ui";ctx.fillText(world.icon,landmark.x,landmark.y-18);ctx.font="800 13px system-ui";ctx.fillStyle="#fff";ctx.fillText(world.name.toUpperCase(),landmark.x,landmark.y+8);
   if(!lake)props.forEach(([px,py,emoji],i)=>{const p=iso(px,py);ctx.font=`${38+(i%3)*4}px system-ui`;ctx.fillText(world.theme==="neon"&&emoji==="🌲"?"🏙️":emoji,p.x,p.y)});
   const p=iso(actor.current.x,actor.current.y);avatarDraw(p.x,p.y,actor.current.head);ctx.font="800 13px system-ui";ctx.fillStyle="#fff";ctx.shadowColor="#102739";ctx.shadowBlur=5;ctx.fillText(username,p.x,p.y-(lake?40:80));ctx.shadowBlur=0;if(bubble){const bw=Math.min(240,Math.max(92,bubble.length*7));ctx.fillStyle="#fff";ctx.beginPath();ctx.roundRect(p.x-bw/2,p.y-(lake?94:135),bw,35,14);ctx.fill();ctx.fillStyle="#243348";ctx.font="600 12px system-ui";ctx.fillText(bubble,p.x,p.y-(lake?72:113))}
  };
  const loop=(t:number)=>{const dt=Math.min(.05,(t-last)/1000);last=t;const k=keys.current,j=joy.current,ix=(k.has("KeyD")||k.has("ArrowRight")?1:0)-(k.has("KeyA")||k.has("ArrowLeft")?1:0)+j.x,iy=(k.has("KeyS")||k.has("ArrowDown")?1:0)-(k.has("KeyW")||k.has("ArrowUp")?1:0)+j.y,mag=Math.min(1,Math.hypot(ix,iy));const a=actor.current;if(mag>.04){const target=Math.atan2(ix,-iy);let diff=target-a.head;while(diff>Math.PI)diff-=TAU;while(diff<-Math.PI)diff+=TAU;a.head+=diff*Math.min(1,dt*9);a.speed=Math.min(lake?150:175,a.speed+(lake?90:380)*dt)}else a.speed=Math.max(0,a.speed-(lake?150:520)*dt);a.x+=Math.sin(a.head)*a.speed*dt;a.y-=Math.cos(a.head)*a.speed*dt;const radius=lake?570:600,d=Math.hypot(a.x,a.y);if(d>radius){a.x*=radius/d;a.y*=radius/d;a.speed*=.45}cam.current.x+=(a.x-cam.current.x)*Math.min(1,dt*5);cam.current.y+=(a.y-cam.current.y)*Math.min(1,dt*5);
   const f=fishRef.current;if(f.state==="waiting"&&t>=f.at){f.state="reeling";f.progress=.12;f.zone=.2+Math.random()*.6;setFishState("reeling");setStatus("BITE! Hold REEL or Space — keep the fish in the glowing zone!")}else if(f.state==="reeling"){f.marker=clamp(f.marker+(hold.current?-.62:.43)*dt,0,1);f.zone=clamp(f.zone+Math.sin(t*.003)*.16*dt,0.16,.84);const good=Math.abs(f.marker-f.zone)<.16;f.progress=clamp(f.progress+(good?.34:-.17)*dt,0,1);setReel({marker:f.marker,zone:f.zone,progress:f.progress});if(f.progress>=1)finishCatch();else if(f.progress<=0){f.state="idle";setFishState("idle");setStatus("The fish escaped — cast again!")}}
   ctx.setTransform(dpr,0,0,dpr,0,0);drawWorld(t);frame=requestAnimationFrame(loop)};frame=requestAnimationFrame(loop);return()=>{cancelAnimationFrame(frame);removeEventListener("resize",resize)};
 },[avatar,bubble,lake,theme,username,world.icon,world.name,world.theme]);
 function send(e:React.FormEvent){e.preventDefault();const m=message.trim();if(!m)return;setLog(l=>[...l.slice(-12),`${username}: ${m}`]);setBubble(m);setMessage("");onChat();setTimeout(()=>setBubble(""),5000)}
 function joyStart(e:React.PointerEvent<HTMLDivElement>){e.currentTarget.setPointerCapture(e.pointerId);const r=e.currentTarget.getBoundingClientRect(),move=(x:number,y:number)=>{joy.current={x:clamp((x-(r.left+r.width/2))/48,-1,1),y:clamp((y-(r.top+r.height/2))/48,-1,1)}};move(e.clientX,e.clientY)}
 return <main className="ehEngine"><canvas ref={canvas}/><header className="ehWorldHud"><button onClick={onExit}>← Leave</button><div><b>{world.icon} {world.name}</b><small>EVERHOME WORLD · {lake?"FISHING GAME":"EXPLORE"}</small></div><button onClick={()=>setPeople(!people)}>♙ People</button></header><canvas className="ehMinimap" width="128" height="86"/><div className="ehNameplate"><span>◆ EXPLORER</span><b>{username}</b></div><div className="ehJoy" onPointerDown={joyStart} onPointerMove={e=>{if(e.currentTarget.hasPointerCapture(e.pointerId))joyStart(e)}} onPointerUp={e=>{joy.current={x:0,y:0};e.currentTarget.releasePointerCapture(e.pointerId)}} onPointerCancel={()=>joy.current={x:0,y:0}}><i style={{transform:`translate(calc(-50% + ${joy.current.x*38}px),calc(-50% + ${joy.current.y*38}px))`}}/></div><div className="ehHint">WASD / arrows · drag joystick to move</div>
 {lake&&<aside className="ehFishing"><header><div><small>EVERHOME MINI GAME</small><b>🎣 THE LAKE</b></div><span>🎒 {bag.length}</span></header><p>{status}</p>{fishState==="reeling"&&<div className="reelGame"><div className="reelTrack"><i style={{top:`${reel.zone*100}%`}}/><b style={{top:`${reel.marker*100}%`}}>🐟</b></div><div className="reelProgress"><i style={{width:`${reel.progress*100}%`}}/></div></div>}<button disabled={fishState==="waiting"||fishState==="caught"} onClick={()=>fishState==="idle"?cast():null} onPointerDown={()=>hold.current=true} onPointerUp={()=>hold.current=false} onPointerCancel={()=>hold.current=false}>{fishState==="idle"?"🎣 CAST LINE":fishState==="waiting"?"〰 WAITING…":"⬆ HOLD TO REEL"}</button>{bag.length>0&&<div className="catchStrip">{bag.slice(-3).reverse().map((f,i)=><span key={i}>{f.icon} <b>{f.name}</b><small>{f.size} cm</small></span>)}</div>}</aside>}
 <button className="fishChatChip ehChatButton" onClick={()=>setChat(!chat)}>💬<span className="fishUnread">2</span><span className="fishOnline">1</span></button>{chat&&<section className="fishChatPanel ehChat"><header><b>💬 World Chat</b><span>🟢 1 player online</span><button onClick={()=>setChat(false)}>✕</button></header><div className="fishChatLog">{log.map((m,i)=>{const n=m.split(":")[0],text=m.slice(m.indexOf(":")+1);return <p className={n===username?"mine":""} key={i}><b>{n}</b> <span>{text}</span></p>})}</div><form onSubmit={send}><input value={message} onChange={e=>setMessage(e.target.value)} placeholder="Say something…" maxLength={120}/><button>➤</button></form></section>}{people&&<aside className="ehPeople"><header><b>People here</b><button onClick={()=>setPeople(false)}>×</button></header><p>👩🏽 <b>Mira</b><button>＋</button></p><p>🧑🏻 <b>Kairo</b><button>＋</button></p><p>🙂 <b>{username}</b><small>You</small></p></aside>}</main>
}
